### ISSUE TITLE
Traceback [Errno 2] No such file or directory: '/data/dl-data/couplet/vocabs'

### ISSUE THREAD

**Issue by Crescentz** [wb14123/seq2seq-couplet#10]
Traceback (most recent call last):
  File "D:/CODE/project/tensorflow/seq2seq-couplet/couplet.py", line 13, in <module>
    restore_model=False)
  File "D:\CODE\project\tensorflow\seq2seq-couplet\model.py", line 33, in __init__
    train_target_file, vocab_file, batch_size)
  File "D:\CODE\project\tensorflow\seq2seq-couplet\reader.py", line 50, in __init__
    self.vocabs = read_vocab(vocab_file)
  File "D:\CODE\project\tensorflow\seq2seq-couplet\reader.py", line 33, in read_vocab
    f = open(vocab_file, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/data/dl-data/couplet/vocabs'

**Comment by 390962851** [comment]
解决没？我也遇到了 好像换成绝对路径就可以了
