### ISSUE TITLE
请问tensorflow版本是多少呀？

### ISSUE THREAD

**Issue by Hoke** [wb14123/seq2seq-couplet#24]
请问我们这工程用的tensorflow版本是多少呀？我现在用的是tensorflow 1.11.0的版本，但运行couplet.py训练模型的过程中出现如下错误：

"D:\Program Files\Anaconda3\python.exe" K:/other_proj/seq2seq-couplet-master/couplet.py
D:\Program Files\Anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
WARNING:tensorflow:From K:\other_proj\seq2seq-couplet-master\seq2seq.py:12: BasicLSTMCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is deprecated, please use tf.nn.rnn_cell.LSTMCell, which supports all the feature this cell currently has. Please replace the existing code with tf.nn.rnn_cell.LSTMCell(name='basic_lstm_cell').
2019-01-21 10:06:30.391998: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Reloading model file before training.
Saving model. Step: 0, loss: 0.956932
******************************
src: 龙 湾 子 携 龙 坨 女 ， 龙 舟 赛 上 龙 腾 虎 跃
output: ， ，
target: 马 王 爷 带 马 云 孙 ， 马 街 书 会 马 壮 人 强
====================
src:天 涯 寻 醉 客
output: 
target: 海 角 觅 诗 行
====================
src:凡 却 非 凡 ， 半 坡 烟 雨 国 风 里
output: ，
target: 了 而 未 了 ， 一 卷 文 心 吾 爱 中
====================
src:分 牝 牡
output: 
target: 辨 雄 雌
====================
src:春 绿 千 村 ， 碧 江 共 旗 山 一 色
output: ，
target: 政 兴 百 业 ， 红 木 与 牛 仔 双 名
====================
src:溪 头 几 串 童 年 梦
output: 
target: 心 底 一 支 岁 月 歌
====================
src:不 欲 干 鞋 沾 湿 水
output: 
target: 何 妨 赤 脚 濯 清 流
Evaluate model. Step: 0, score: 0.000000, loss: 0.956932
2019-01-21 10:12:55.659938: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_136/gradients/decoder/while/BasicDecoderStep/decoder/attention_wrapper/bahdanau_attention/mul/Enter_1_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/struct tensorflow::TemporaryVariableOp::TmpVar
2019-01-21 10:12:56.320540: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_136/gradients/decoder/while/BasicDecoderStep/decoder/attention_wrapper/bahdanau_attention/mul/Enter_1_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/struct tensorflow::TemporaryVariableOp::TmpVar
2019-01-21 10:12:56.545342: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_136/gradients/decoder/while/BasicDecoderStep/decoder/attention_wrapper/bahdanau_attention/mul/Enter_1_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/struct tensorflow::TemporaryVariableOp::TmpVar
2019-01-21 10:12:56.794942: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_136/gradients/decoder/while/BasicDecoderStep/decoder/attention_wrapper/bahdanau_attention/mul/Enter_1_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/struct tensorflow::TemporaryVariableOp::TmpVar
2019-01-21 10:12:57.013343: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_136/gradients/decoder/while/BasicDecoderStep/decoder/attention_wrapper/bahdanau_attention/mul/Enter_1_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/struct tensorflow::TemporaryVariableOp::TmpVar
2019-01-21 10:12:57.233946: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_136/gradients/decoder/while/BasicDecoderStep/decoder/attention_wrapper/bahdanau_attention/mul/Enter_1_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/struct tensorflow::TemporaryVariableOp::TmpVar
2019-01-21 10:12:57.498948: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_136/gradients/decoder/while/BasicDecoderStep/decoder/attention_wrapper/bahdanau_attention/mul/Enter_1_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/struct tensorflow::TemporaryVariableOp::TmpVar
2019-01-21 10:12:57.717348: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_136/gradients/decoder/while/BasicDecoderStep/decoder/attention_wrapper/bahdanau_attention/mul/Enter_1_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/struct tensorflow::TemporaryVariableOp::TmpVar
2019-01-21 10:12:57.966949: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_136/gradients/decoder/while/BasicDecoderStep/decoder/attention_wrapper/bahdanau_attention/mul/Enter_1_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/struct tensorflow::TemporaryVariableOp::TmpVar
2019-01-21 10:12:58.214553: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_136/gradients/decoder/while/BasicDecoderStep/decoder/attention_wrapper/bahdanau_attention/mul/Enter_1_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/struct tensorflow::TemporaryVariableOp::TmpVar
2019-01-21 10:12:58.428354: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_136/gradients/decoder/while/BasicDecoderStep/decoder/attention_wrapper/bahdanau_attention/mul/Enter_1_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/struct tensorflow::TemporaryVariableOp::TmpVar
2019-01-21 10:12:58.678955: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_136/gradients/decoder/while/BasicDecoderStep/decoder/attention_wrapper/bahdanau_attention/mul/Enter_1_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/struct tensorflow::TemporaryVariableOp::TmpVar
2019-01-21 10:12:58.881755: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_136/gradients/decoder/while/BasicDecoderStep/decoder/attention_wrapper/bahdanau_attention/mul/Enter_1_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/struct tensorflow::TemporaryVariableOp::TmpVar
2019-01-21 10:12:59.141356: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_136/gradients/decoder/while/BasicDecoderStep/decoder/attention_wrapper/bahdanau_attention/mul/Enter_1_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/struct tensorflow::TemporaryVariableOp::TmpVar
2019-01-21 10:12:59.357157: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_136/gradients/decoder/while/BasicDecoderStep/decoder/attention_wrapper/bahdanau_attention/mul/Enter_1_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/struct tensorflow::TemporaryVariableOp::TmpVar
2019-01-21 10:12:59.591158: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_136/gradients/decoder/while/BasicDecoderStep/decoder/attention_wrapper/bahdanau_attention/mul/Enter_1_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/struct tensorflow::TemporaryVariableOp::TmpVar
2019-01-21 10:12:59.809558: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_136/gradients/decoder/while/BasicDecoderStep/decoder/attention_wrapper/bahdanau_attention/mul/Enter_1_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/struct tensorflow::TemporaryVariableOp::TmpVar
2019-01-21 10:13:00.027959: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_136/gradients/decoder/while/BasicDecoderStep/decoder/attention_wrapper/bahdanau_attention/mul/Enter_1_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/struct tensorflow::TemporaryVariableOp::TmpVar
2019-01-21 10:13:00.269563: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_136/gradients/decoder/while/BasicDecoderStep/decoder/attention_wrapper/bahdanau_attention/mul/Enter_1_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/struct tensorflow::TemporaryVariableOp::TmpVar
2019-01-21 10:13:00.524771: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_136/gradients/decoder/while/BasicDecoderStep/decoder/attention_wrapper/bahdanau_attention/mul/Enter_1_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/struct tensorflow::TemporaryVariableOp::TmpVar
2019-01-21 10:13:00.743172: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_136/gradients/decoder/while/BasicDecoderStep/decoder/attention_wrapper/bahdanau_attention/mul/Enter_1_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/struct tensorflow::TemporaryVariableOp::TmpVar
2019-01-21 10:13:00.977172: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_136/gradients/decoder/while/BasicDecoderStep/decoder/attention_wrapper/bahdanau_attention/mul/Enter_1_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/struct tensorflow::TemporaryVariableOp::TmpVar
2019-01-21 10:13:01.214173: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_136/gradients/decoder/while/BasicDecoderStep/decoder/attention_wrapper/bahdanau_attention/mul/Enter_1_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/struct tensorflow::TemporaryVariableOp::TmpVar
2019-01-21 10:13:01.448376: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_136/gradients/decoder/while/BasicDecoderStep/decoder/attention_wrapper/bahdanau_attention/mul/Enter_1_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/struct tensorflow::TemporaryVariableOp::TmpVar
2019-01-21 10:13:01.666776: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_136/gradients/decoder/while/BasicDecoderStep/decoder/attention_wrapper/bahdanau_attention/mul/Enter_1_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/struct tensorflow::TemporaryVariableOp::TmpVar
2019-01-21 10:13:01.885177: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_136/gradients/decoder/while/BasicDecoderStep/decoder/attention_wrapper/bahdanau_attention/mul/Enter_1_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/struct tensorflow::TemporaryVariableOp::TmpVar
2019-01-21 10:13:02.119177: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_136/gradients/decoder/while/BasicDecoderStep/decoder/attention_wrapper/bahdanau_attention/mul/Enter_1_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/struct tensorflow::TemporaryVariableOp::TmpVar
Traceback (most recent call last):
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1292, in _do_call
    return fn(*args)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1277, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1367, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.AlreadyExistsError: Resource __per_step_136/gradients/decoder/while/BasicDecoderStep/decoder/attention_wrapper/bahdanau_attention/mul/Enter_1_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/struct tensorflow::TemporaryVariableOp::TmpVar
	 [[{{node gradients/decoder/while/BasicDecoderStep/decoder/attention_wrapper/bahdanau_attention/mul/Enter_1_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var}} = TemporaryVariable[dtype=DT_FLOAT, shape=[1024], var_name="gradients/...dd/tmp_var", _device="/job:localhost/replica:0/task:0/device:CPU:0"](^gradients/decoder/while/BasicDecoderStep/decoder/attention_wrapper/bahdanau_attention/mul_grad/Mul_1)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "K:/other_proj/seq2seq-couplet-master/couplet.py", line 15, in <module>
    m.train(50000)
  File "K:\other_proj\seq2seq-couplet-master\model.py", line 135, in train
    self.train_target_seq_len: target_seq_len})
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 887, in run
    run_metadata_ptr)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1110, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1286, in _do_run
    run_metadata)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1308, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.AlreadyExistsError: Resource __per_step_136/gradients/decoder/while/BasicDecoderStep/decoder/attention_wrapper/bahdanau_attention/mul/Enter_1_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/struct tensorflow::TemporaryVariableOp::TmpVar
	 [[{{node gradients/decoder/while/BasicDecoderStep/decoder/attention_wrapper/bahdanau_attention/mul/Enter_1_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var}} = TemporaryVariable[dtype=DT_FLOAT, shape=[1024], var_name="gradients/...dd/tmp_var", _device="/job:localhost/replica:0/task:0/device:CPU:0"](^gradients/decoder/while/BasicDecoderStep/decoder/attention_wrapper/bahdanau_attention/mul_grad/Mul_1)]]

Process finished with exit code 1

**Comment by wb14123** [comment]
Tensorflow 版本 1.7.0

**Comment by Hoke** [comment]
谢谢，是tensorflow版本的问题，现在训练不会出错了。
