### ISSUE TITLE
运行完couplet.py后运行server.py时遇到问题

### ISSUE THREAD

**Issue by info-wyf** [wb14123/seq2seq-couplet#5]
2018-04-12 15:19:39.686884: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-04-12 15:19:39.763650: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:170 : Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /Users/info_kerwin/Desktop/seq2seq/data/dl-data/models/tf-lib/output_couplet_prod/model.ckpl

couplet.py训练完后的数据是四个：model.ckpl.data-00000-of-00001、model.ckpl.index、model.ckpl.meta、checkpoint，运行server.py是如何产生model.ckpl文件的？

**Comment by wb14123** [comment]
训练之后生成的文件默认在 `/data/dl-data/models/tf-lib/output_couple`，`server.py` 默认从  `/data/dl-data/models/tf-lib/output_couple_prod` 读取文件，所以把文件夹重命名或者改一下读取的地址就好了

**Comment by info-wyf** [comment]
感谢,运行完后好像卡住了，不知道server.py运行多长时间会构建好服务

2018-04-12 16:58 GMT+08:00, Bin Wang <notifications@github.com>:

**Comment by wb14123** [comment]
server.py 目前没有输出，可以浏览器访问一下 localhost:5000 看是不是已经启动了

**Comment by info-wyf** [comment]
您好，我运行了server后，打开localhost:5000，发现返回的是：
::1 - - [2018-04-13 15:58:56] "GET / HTTP/1.1" 404 374 0.019463

将此服务停止，返回timeout信息，如下：

Fri Apr 13 15:49:40 2018
Traceback (most recent call last):
  File "server.py", line 34, in <module>
    http_server.serve_forever()
  File "/Users/xxx/anaconda3/lib/python3.6/site-packages/gevent/baseserver.py", line 362, in serve_forever
    self._stop_event.wait()
  File "/Users/xxx/anaconda3/lib/python3.6/site-packages/gevent/event.py", line 219, in wait
    return self._wait(timeout)
  File "/Users/xxx/anaconda3/lib/python3.6/site-packages/gevent/event.py", line 129, in _wait
    gotit = self._wait_core(timeout)
  File "/Users/xxx/anaconda3/lib/python3.6/site-packages/gevent/event.py", line 106, in _wait_core
    result = self.hub.switch()
  File "/Users/xxx/anaconda3/lib/python3.6/site-packages/gevent/hub.py", line 630, in switch
    return RawGreenlet.switch(self)


不知运行server.py时是否还有其他需要注意的？

**Comment by info-wyf** [comment]
ok，运行成功，感谢
