### ISSUE TITLE
大佬来看看这个怎么解决啊！！！！

### ISSUE THREAD

**Issue by DaemonicCao** [wb14123/seq2seq-couplet#75]
Traceback (most recent call last):
  File "D:/seq2seq-couplet-master/couplet.py", line 23, in <module>
    m.train(5000000)
  File "D:\seq2seq-couplet-master\model.py", line 164, in train
    bleu_score = self.eval(step)
  File "D:\seq2seq-couplet-master\model.py", line 194, in eval
    self.eval_reader.vocabs).split(' ')
  File "D:\seq2seq-couplet-master\reader.py", line 25, in decode_text
    word = vocabs[idx]
TypeError: only integer scalar arrays can be converted to a scalar index

进程已结束,退出代码1

**Comment by Lijiaxing-lx** [comment]
您好，邮件已收到。我将尽快给你回复。

**Comment by zhoujinyang1996** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by DaemonicCao** [comment]
感谢🙏

发自我的iPhone

**Comment by xiaoshuai1** [comment]
同问

**Comment by zhoujinyang1996** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Lijiaxing-lx** [comment]
您好，邮件已收到。我将尽快给你回复。

**Comment by Drizzlenum** [comment]
> 

请问跑通了吗

**Comment by cui-z** [comment]
word = vocabs[idx]  修改为
word = np.array(vocabs)[idx]

**Comment by LongHuW** [comment]
我这边是因为labels出现了三维array这种数据，所以我加了一个步骤，将其降维成一维就好了
def decode_text(labels, vocabs, end_token = '</s>'):
    results = []
    if isinstance(labels, list) == False and labels.ndim>1:
        labels_one = labels.reshape(-1)
        for idx in labels_one:
            word = vocabs[idx]
            if word == end_token:
                return ' '.join(results)
            results.append(word)
        return ' '.join(results)

    for idx in labels:
        word = vocabs[idx]
        if word == end_token:
            return ' '.join(results)
        results.append(word)
    return ' '.join(results)

**Comment by DaemonicCao** [comment]
感谢🙏

发自我的iPhone

**Comment by weifang74** [comment]
> 我这边是因为labels出现了三维array这种数据，所以我加了一个步骤，将其降维成一维就好了
> 
> ```
> def decode_text(labels, vocabs, end_token = '</s>'):
>     results = []
>     if isinstance(labels, list) == False and labels.ndim>1:
>         labels_one = labels.reshape(-1).astype(int)
>         for idx in labels_one:
>             word = vocabs[idx]
>             if word == end_token:
>                 return ' '.join(results)
>             results.append(word)
>         return ' '.join(results)
> 
>     for idx in labels:
>         word = vocabs[idx]
>         if word == end_token:
>             return ' '.join(results)
>         results.append(word)
>     return ' '.join(results)
> ```

我这边也是这个问题，跑起来了，就是不知道这样改有问题没
