### ISSUE TITLE
运行python ls

### ISSUE THREAD

**Issue by monkey-19890212** [wb14123/seq2seq-couplet#83]

**Comment by monkey-19890212** [comment]
Skipping registering GPU devices...
2023-05-31 09:39:48.947261: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2023-05-31 09:39:48.947267: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0
2023-05-31 09:39:48.947280: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N
2023-05-31 09:39:49.426814: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-05-31 09:39:49.426961: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: NVIDIA GeForce RTX 3050 major: 8 minor: 6 memoryClockRate(GHz): 1.792
pciBusID: 0000:07:00.0
2023-05-31 09:39:49.427063: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudart.so.10.0'; dlerror: libcudart.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2023-05-31 09:39:49.427107: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcublas.so.10.0'; dlerror: libcublas.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2023-05-31 09:39:49.427157: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcufft.so.10.0'; dlerror: libcufft.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2023-05-31 09:39:49.427199: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcurand.so.10.0'; dlerror: libcurand.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2023-05-31 09:39:49.427232: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusolver.so.10.0'; dlerror: libcusolver.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2023-05-31 09:39:49.427274: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusparse.so.10.0'; dlerror: libcusparse.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2023-05-31 09:39:49.427326: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudnn.so.7'; dlerror: libcudnn.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2023-05-31 09:39:49.427336: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1641] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2023-05-31 09:39:49.427351: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2023-05-31 09:39:49.427357: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0
2023-05-31 09:39:49.427363: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N
Saving model. Step: 0, loss: 0.877713
******************************
Traceback (most recent call last):
  File "couplet.py", line 15, in <module>
    m.train(50)
  File "/root/chat/Chinese_Couplet/model.py", line 166, in train
    print('src: ' + input_text)
UnicodeEncodeError: 'ascii' codec can't encode character '\u7389' in position 5: ordinal not in range(128)

**Comment by monkey-19890212** [comment]
数据集使用的https://github.com/wb14123/couplet-dataset/releases/download/1.0/couplet.tar.gz

**Comment by zhangzzz29** [comment]
请问你解决这个问题了吗
